title: Chaya Trapedo
theme: jekyll-theme-minimal
logo: /assets/headshot_circle.png
description: [Download Resume](/assets/Chaya_Trapedo_resume.pdf)
description: [LinkedIn](https://www.linkedin.com/in/chayatrapedo/)
description: [Email](mailto:chayatrapedo@gmail.com)
