title: Chaya Trapedo
theme: jekyll-theme-minimal
logo: /assets/headshot_circle.png
# description: |
#   [Download Resume](/assets/Chaya_Trapedo_resume.pdf) 
#   [LinkedIn](https://www.linkedin.com/in/chayatrapedo/) 
#   [Email](mailto:chayatrapedo@gmail.com)
